### ISSUE TITLE
ExternalRoutineInvocationException: Need password for secret key

### ISSUE THREAD

**Issue by guiflemes** [incuna/django-pgcrypto-fields#351] opened 2021-05-05 19:57 UTC
I made all the configurations described in the README to use ` PGPPublicKeyField`.
I created my public and private key, however when I make a query this error is thrown, `ExternalRoutineInvocationException: Need password for secret key`

Am I missing something?

**Comment by peterfarrell** [comment] 2021-06-12 17:26
See:

https://github.com/incuna/django-pgcrypto-fields/blob/master/README.md#limitations

PR welcomed on:

https://github.com/incuna/django-pgcrypto-fields/issues/89

**Comment by peterfarrell** [comment] 2021-06-12 17:33
This is a duplicate of #89. Closing.

**Closed by peterfarrell** 2021-06-12 17:33 UTC
Labels: duplicate, question
